# Generated by Django 5.0 on 2023-12-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
